name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
      
      - name: Configure Git
        uses: actions/setup-git@v2
        with:
          user-email: magtutofrancis@gmail.com
          user-name: kingfrancis03

      - name: Build
        run: CI=false npm run deploy

